services:
  redis:
    image: redis:7-alpine
    container_name: loggery-redis

    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD:-loggery-password}

    ports:
      - "6379:6379"

    volumes:
      - redis_data:/data

    command: redis-server  --requirepass ${REDIS_PASSWORD:-loggery-password} --appendonly yes --maxmemory-policy allkeys-lru

    restart: unless-stopped

    healthcheck:
      test:
        [
          "CMD",
          "redis-cli",
          "-a",
          "${REDIS_PASSWORD:-loggery-password}",
          "ping",
        ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  redis_data: